## YAML File
version: '3'
services:
 administrator:
  build:
   context: ./Administrator/
  #image: alokdethe/ubuntu-common
  ports:
   - "8081:8080"
      
 entity:
  build:
   context: ./Entity/
  #image: alokdethe/ubuntu-common
  ports:
   - "8082:8080"
      
 reports:
  build:
   context: ./Reports/
  #image: alokdethe/ubuntu-common
  ports:
   - "8083:8080"
       
 gateway:
  build:
   context: ./Gateway/
  #image: alokdethe/ubuntu-common
  ports:
   - "8084:8080"
