## YAML File
version: '3'
services:
  administrator:
    build:
      context: ./Administrator/
    image: alpine
    ports:
      - "8081:8080"
    #depends_on:
      #- mysql
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      #SPRING_DATASOURCE_USERNAME: mysqluser
      #SPRING_DATASOURCE_PASSWORD: mysqlpw
      #SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
  
  entity:
    build:
      context: ./Entity/
    image: alpine
    ports:
      - "8082:8080"
    #depends_on:
      #- mysql
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      #SPRING_DATASOURCE_USERNAME: mysqluser
      #SPRING_DATASOURCE_PASSWORD: mysqlpw
      #SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      

  reports:
    build:
      context: ./Reports/
    image: alpine
    ports:
      - "8083:8080"
    #depends_on:
      #- mysql
    

   gateway:
     build:
      context: ./Gateway/
     image: alpine
     ports:
      - "8084:8080"
    #depends_on:
      #- mysql
    
  

  #mysql:
    #image: 
    #ports:
      #- 3306:3306
    #environment:
      #- MYSQL_ROOT_PASSWORD=rootpassword
      #- MYSQL_USER=mysqluser
      #- MYSQL_PASSWORD=mysqlpw


