ARG baseImageVersion=3.4
FROM alokdethe/ubuntu-common
MAINTAINER Alok Dethe
CMD /usr/local/tomcat/bin/catalina.sh run
#Copy JAR and run the Service in the container
#COPY Administrator-1.0-SNAPSHOT.jar service.jar
#EXPOSE 8877

